name: Build & Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled'
        required: false
        default: false

env:
  EMSDK_VERSION: 4.0.5

jobs:
  build:
    runs-on: ubuntu-24.04
    if: |
      !contains(github.event.head_commit.message, 'skip-ci')

    steps:
    - uses: actions/checkout@v4

    - name: Build WASM lib
      run: |
        npm run build:docker
        npm run build:emscripten

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: lib
        path: |
          built/bin/wiregasm.*

    - name: Load Dependencies
      run: npm ci

    - name: Run Tests
      run: npm test
